// Master list of cities available in the flight reservation system.
// Used by SearchBar (homepage) and SearchFlights (search page) for autocomplete.

export const CITIES = [
  // Indian Cities
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Goa",
  "Chandigarh",
  "Lucknow",
  "Amritsar",
  "Kochi",
  "Surat",
  "Nagpur",
  "Indore",
  "Bhopal",
  "Vadodara",
  "Coimbatore",
  "Vizag",
  "Thiruvananthapuram",
  "Patna",
  "Ranchi",
  "Bhubaneswar",
  "Raipur",
  "Jammu",
  "Srinagar",
  "Leh",
  "Jodhpur",
  "Udaipur",
  "Aurangabad",
  "Mangalore",
  "Madurai",
  "Varanasi",
  "Agra",
  "Dehradun",

  // International Airports / Cities
  "Dubai",
  "Singapore",
  "London",
  "New York",
  "Bangkok",
  "Tokyo",
  "Kathmandu",
  "Colombo",
  "Kuala Lumpur",
  "Hong Kong",
  "Sydney",
  "Paris",
  "Toronto",
  "Frankfurt",
  "Amsterdam",
  "Doha",
  "Abu Dhabi",
  "Bahrain",
  "Muscat",
  "Nairobi",
  "Johannesburg",
  "Beijing",
  "Shanghai",
  "Seoul",
  "Osaka",
  "Male",
  "Dhaka",
  "Lahore",
  "Karachi",
];
